env:
  node: true
  es2020: false
parserOptions:
  ecmaVersion: 2017
extends:
  - 'eslint:recommended'
  - prettier
plugins:
  - prettier
rules:
  prettier/prettier: error
  prefer-destructuring:
    - error
    - object: true
      array: false
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
