env:
  node: true
  es2020: true
parserOptions:
  ecmaVersion: 11
extends:
  - 'eslint:recommended'
  - prettier
plugins:
  - prettier
rules:
  prettier/prettier: error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
